import {
  tankOne,
shirtOne,
sweatOne,
fourShirt,
shirtThree,
sweatTwo,
tankTwo,
shirtFour, 
twoShirt,
shirtFive,

hoodieOne,
hoodieTwo,
hoodieThree,
hoodieFour,
pantsOne,
pantsTwo,
pantsThree,
pantsFour,
pantsFive,

capOne,
capTwo,
capFour,
capThree,
shortOne,
shortTwo,
shortThree,

  
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },

];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: tankOne,
    productName: "HASHTAG GECK TANK TOP",
    price: "12,000",
    color: "Black, Ash and Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flux Design at front. Comfy Neck Band on the Shirt. No sleeves.",
  },
  {
    _id: "202",
    img: shirtOne,
    productName: "HASHTAG BLOCK SWEATSHIRT",
    price: "20,000",
    color: "Black, Ash and Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck and Wrist Elastic Band.",
  },
  {
    _id: "203",
    img: pantsOne,
    productName: "HASHTAG CROPPED TOP",
    price: "10,000",
    color: "Black, Ash and Brown",
    badge: true,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck Band on the Shirt. Cropped and mainly for Women",
  },
  {
    _id: "204",
    img: capOne,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: tankOne,
    productName: "HASHTAG GECK TANK TOP",
    price: "12,000",
    color: "Black, Brown & Ash",
    // badge: true,
    des: "100% Cotton Solid Color. Flux Design at front. Comfy Neck Band on the Shirt. No sleeves.",
  },
  {
    _id: 1002,
    img: capThree,
    productName: "HASHTAG WAVE CAP",
    price: "5,000",
    color: "Mixed",
  
    des: "100% Cotton, Soft Comfortable Band Around the edges. Expandable Rubber Like Texture.",
  },
  {
    _id: 1003,
    img: shirtFive,
    productName: "HASHTAG STRIPES T-SHIRT",
    price: "25,000",
    color: "Black, Brown & Ash",
    badge: true,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy  Collar Wide and Comfortable on the Shirt",
  },
  {
    _id: 1004,
    img: capFour,
    productName: "HASHTAG SNAPBACK HAT",
    price: "12,000",
    color: "Mixed",
    
    des: "100% Cotton, Soft Gum-Stay in front, Plastic Adjustable Clip at the back, Cotton Net back cover",
  },
  {
    _id: 1005,
    img: shirtThree,
    productName: "HASHTAG BLOCK TEES",
    price: "15,000",
    color: "Black, Ash & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck Band on the Shirt",
  },
  {
    _id: 1006,
    img: sweatTwo,
    productName: "HASHTAG GECK SWEATSHIRT",
    price: "20,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck and Wrist Elastic Band.",
  },
  {
    _id: 1007,
    img: pantsTwo,
    productName: "HASHTAG SNOW JOGGERS",
    price: "20,000",
    color: "Black, Ash  & Brown",
    // badge: true,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Waist and Ankle Elastic Band. Drawstring Casual Fleece Joggers.",
  },
  {
    _id: 1008,
    img: shirtFour,
    productName: "HASHTAG GECK CROPPED",
    price: "20,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck Band on the Shirt. Cropped and mainly for Men.",
  },
  {
    _id: 1009,
    img: pantsFour,
    productName: "HASHTAG BLOCK JOGGERS",
    price: "20,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Waist and Ankle Elastic Band. Drawstring Casual Fleece Joggers..",
  },
  {
    _id: 1010,
    img: fourShirt,
    productName: "HASHTAG MIX 1 TEES",
    price: "16,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck Band on the Shirt",
  },
  {
    _id: 1011,
    img: capTwo,
    productName: "HASHTAG TUNKER HAT",
    price: "5,000",
    color: "Mixed",
    badge: false,
    des: "100% Cotton, Soft Foam in front, Plastic Adjustable Clip at the back, Cotton Net back cover.",
  },
  {
    _id: 1012,
    img: tankTwo,
    productName: "HASHTAG GYM TANK TOP",
    price: "12,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Monogram Design at front. Comfy Neck Band on the Shirt. No sleeves.",
  },
  {
    _id: 1013,
    img: twoShirt,
    productName: "HASHTAG MIX 2 TEES",
    price: "15,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck Band on the Shirt",
  },

  {
    _id: 1014,
    img: hoodieOne,
    productName: "HASHTAG SNOW HOODIE",
    price: "26,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color Hooded. Drawstring Casual Fleece Hoodie. Flock Design at front.",
  },
  {
    _id: 1015,
    img: pantsThree,
    productName: "HASHTAG GECK JOGGERS",
    price: "20,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flux Design at front. Comfy Waist and Ankle Elastic Band. Drawstring Casual Fleece Joggers.",
  },
  {
    _id: 1016,
    img: pantsFive,
    productName: "HASHTAG GECK PANTS",
    price: "22,000",
    color: "Black, Ash  & Brown",
    // badge: true,
    des: "100% Cotton Solid Color. Flux Design at front. Comfy Waist Elastic Band. Drawstring Casual Fleece Pants.",
  },
  {
    _id: 1017,
    img: hoodieThree,
    productName: "HASHTAG BLOCK HOODIE",
    price: "26,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color Hooded. Drawstring Casual Fleece Hoodie. Flock Design at front.",
  },
  {
    _id: 1018,
    img: hoodieFour,
    productName: "HASHTAG CROPPED ZIP-UP HOODIE",
    price: "22,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color Hooded. Drawstring Casual Fleece Hoodie. Flux Design at front. Cropped and mainly for Women. Metal Zipper.",
  },
  {
    _id: 1019,
    img: hoodieTwo,
    productName: "HASHTAG OVERSIZED ZIP-UP HOODIE",
    price: "20,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color Hooded. Drawstring Casual Fleece Hoodie. Flux Design at front. Metal Zipper",
  },
  {
    _id: 1020,
    img: sweatOne,
    productName: "HASHTAG BLOCK SWEATSHIRT",
    price: "20,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy Neck and Wrist Elastic Band.",
  },
  {
    _id: 1021,
    img: shortOne,
    productName: "HASHTAG BLOCK SHORTS ",
    price: "15,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy  Waist Elastic Band. Drawstring Casual Fleece Shorts.",
  },
  {
    _id: 1022,
    img: shortTwo,
    productName: "HASHTAG GYM SHORTS",
    price: "15,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flock Design at front. Comfy  Waist Elastic Band. Drawstring Casual Fleece Shorts.",
  },
  {
    _id: 1023,
    img: shortThree,
    productName: "HASHTAG GECK SHORTS ",
    price: "15,000",
    color: "Black, Ash  & Brown",
    badge: false,
    des: "100% Cotton Solid Color. Flux Design at front. Comfy  Waist Elastic Band. Drawstring Casual Fleece Shorts.",
  },
  // {
  //   _id: 1024,
  //   img: shortFour,
  //   productName: "Cap for Boys",
  //   price: "35.00",
  //   color: "Blank and White",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1025,
  //   img: spfTwo,
  //   productName: "Tea Table",
  //   price: "180.00",
  //   color: "Gray",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1026,
  //   img: spfThree,
  //   productName: "Headphones",
  //   price: "25.00",
  //   color: "Mixed",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1027,
  //   img: spfFour,
  //   productName: "Sun glasses",
  //   price: "220.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1028,
  //   img: bestSellerOne,
  //   productName: "Flower Base",
  //   price: "35.00",
  //   color: "Blank and White",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1029,
  //   img: bestSellerTwo,
  //   productName: "New Backpack",
  //   price: "180.00",
  //   color: "Gray",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1030,
  //   img: bestSellerThree,
  //   productName: "Household materials",
  //   price: "25.00",
  //   color: "Mixed",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1031,
  //   img: bestSellerFour,
  //   productName: "Travel Bag",
  //   price: "220.00",
  //   color: "Black",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1032,
  //   img: newArrOne,
  //   productName: "Round Table Clock",
  //   price: "44.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1033,
  //   img: newArrTwo,
  //   productName: "Smart Watch",
  //   price: "250.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1034,
  //   img: newArrThree,
  //   productName: "cloth Basket",
  //   price: "80.00",
  //   color: "Mixed",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1035,
  //   img: newArrFour,
  //   productName: "Funny toys for babies",
  //   price: "60.00",
  //   color: "Mixed",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1036,
  //   img: newArrTwo,
  //   productName: "Funny toys for babies",
  //   price: "60.00",
  //   color: "Mixed",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1037,
  //   img: newArrFour,
  //   productName: "Funny toys for babies",
  //   price: "60.00",
  //   color: "Mixed",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1038,
  //   img: newArrTwo,
  //   productName: "Smart Watch",
  //   price: "250.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1039,
  //   img: bestSellerFour,
  //   productName: "Travel Bag",
  //   price: "220.00",
  //   color: "Black",
  //   badge: false,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1040,
  //   img: newArrOne,
  //   productName: "Round Table Clock",
  //   price: "44.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1041,
  //   img: newArrTwo,
  //   productName: "Smart Watch",
  //   price: "250.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1042,
  //   img: newArrThree,
  //   productName: "cloth Basket",
  //   price: "80.00",
  //   color: "Mixed",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1043,
  //   img: spfThree,
  //   productName: "Headphones",
  //   price: "25.00",
  //   color: "Mixed",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1044,
  //   img: spfFour,
  //   productName: "Sun glasses",
  //   price: "220.00",
  //   color: "Black",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1045,
  //   img: bestSellerOne,
  //   productName: "Flower Base",
  //   price: "35.00",
  //   color: "Blank and White",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
  // {
  //   _id: 1046,
  //   img: spfOne,
  //   productName: "Cap for Boys",
  //   price: "35.00",
  //   color: "Blank and White",
  //   badge: true,
  //   des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  // },
];
// =================== PaginationItems End here =================
